FROM eclipse-temurin:17

RUN echo '[DOCKER] Building in progress...'
ARG JAR_FILE
RUN echo ${JAR_FILE}
EXPOSE 8095
ADD target/${JAR_FILE} /usr/share/codeonce-ioevent-studio-gen-api/app.jar
ENTRYPOINT ["java", "-jar","/usr/share/codeonce-ioevent-studio-gen-api/app.jar"]
RUN echo '[DOCKER] Build completed!'